# Generated by Django 3.0.6 on 2020-05-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('nutriscore', models.CharField(max_length=1)),
                ('url', models.TextField()),
                ('image', models.TextField()),
                ('category', models.CharField(max_length=250)),
            ],
        ),
    ]
