language: python
python:
  - '3.7'

branches:
  only:
    - staging

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="django_backend.settings"

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=django_backend.settings.travis

script:
  - ./manage.py test
